#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

setbg &			# set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &	# Uncomment to use Xresources colors/settings on startup
xset r rate 300 50 &	# Speed xrate up
xrandr --output $(xrandr | grep "HDMI" | awk 'NR == 1 {print $1}') --mode 1920x1080 #setup HDMI external monitor

autostart="mpd xcompmgr dunst pipewire wireplumber"

for program in $autostart; do
	pidof -s "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
